name: Download Spotify for Ubuntu

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Spotify .deb
        run: |
          curl -L -o spotify.deb https://download.spotify.com/linux/spotify-client_amd64.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-deb
          path: spotify.deb
