name: Download FDM

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Free Download Manager
        run: |
          wget -O freedownloadmanager.deb https://files2.freedownloadmanager.org/latest/freedownloadmanager.deb

      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: FDM-Linux
          path: freedownloadmanager.deb
